spring:
  redis:
    port: 6379
    host: 127.0.0.1
    lettuce:
      pool:
        # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
        max-wait: 10000ms
        # 连接池最大连接数(使用负值表示没有限制) 默认为8
        max-active: 50
        # 连接池中的最大空闲连接 默认为8
        max-idle: 10
        # 连接池中的最小空闲连接 默认为 0
        min-idle: 5
  datasource:
    # 数据库连接地址
    url: jdbc:mysql://127.0.0.1:3306/sky_auth?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf-8&useSSL=true
    # 连接用户名
    username: root
    # 连接密码
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 100
      connection-test-query: SELECT 1

# feigin 配置
feign:
  client:
    config:
      default:
        # 连接超时时间（单位毫秒）
        connectTimeout: 10000
        # 读取超时时间（单位毫秒）
        readTimeout: 10000
  sentinel:
    # 开启sentinel
    enabled: true

# mybatis-plus配置
mybatis-plus:
  # 枚举包
  type-enums-package: com.yanyu.sky.sys.bean.enums
  global-config:
    db-config:
      #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-field: isDel
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
    # 禁止打印banner
    banner: false
  configuration:
    # 打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 暴露端口
management:
  endpoints:
    web:
      exposure:
        include: '*'

# 开启验证码
yanyu:
  security:
    auth:
      image-code-enabled: true